#!/bin/bash

/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONbad_client-Desktop-Debug/JSONbad_client&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONbad_client-Desktop-Debug/JSONbad_client&
/home/student/Projects/JSON_CS/build-JSONbad_client-Desktop-Debug/JSONbad_client&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONbad_client-Desktop-Debug/JSONbad_client&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONbad_client-Desktop-Debug/JSONbad_client&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&
/home/student/Projects/JSON_CS/build-JSONclient-Desktop-Debug/JSONclient&


